name: build-windows-exe
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller --onefile --noconsole ^
             --add-binary "chromedriver\\chromedriver.exe;chromedriver" ^
             --hidden-import openpyxl --hidden-import openpyxl.cell._writer ^
             main.py
      - uses: actions/upload-artifact@v4
        with:
          name: app-windows
          path: dist/*
